import React, { useState, useMemo } from 'react';
import WelcomeScreen from './components/WelcomeScreen';
import CollegeCard from './components/CollegeCard';
import CompareModal from './components/CompareModal';
import CollegeDetailsDrawer from './components/CollegeDetailsDrawer';
import ExamsCatalog from './components/ExamsCatalog';
import { getColleges, ALL_STATES, College } from './data/colleges';
import { 
  GraduationCap, Search, Award, BookOpen, Filter, Map, Clock, 
  RotateCcw, Info, GitCompare, ChevronRight, Check, X, Sparkles, MapPin, 
  Briefcase 
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

export default function App() {
  // Screen States: 'welcome' | 'explorer'
  const [screen, setScreen] = useState<'welcome' | 'explorer'>('welcome');

  // Load procedurally generated colleges (Satisfies exactly 15 top colleges per state across 28 states)
  const masterColleges = useMemo(() => getColleges(), []);

  // Filter & Layout states
  const [selectedState, setSelectedState] = useState<string>('All');
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [activeEventFilter, setActiveEventFilter] = useState<string>('All');
  const [sortBy, setSortBy] = useState<string>('name'); // default sorted alphabetically
  const [activeTab, setActiveTab] = useState<'list' | 'exams'>('list'); // switch between colleges and entrance guides

  // AI Semantic Search States
  const [isAiMode, setIsAiMode] = useState<boolean>(false);
  const [aiMatches, setAiMatches] = useState<string[] | null>(null);
  const [aiRationale, setAiRationale] = useState<string | null>(null);
  const [aiLoading, setAiLoading] = useState<boolean>(false);

  const handleAiSearch = async (val: string) => {
    if (!val.trim()) {
      setAiMatches(null);
      setAiRationale(null);
      return;
    }
    setAiLoading(true);
    setAiRationale(null);
    try {
      const res = await fetch("/api/gemini/search", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ query: val }),
      });
      const data = await res.json();
      if (data.matches) {
        setAiMatches(data.matches);
        setAiRationale(data.rationale);
      } else {
        setAiMatches([]);
        setAiRationale("No matches generated by AI.");
      }
    } catch (err) {
      console.error(err);
      setAiRationale("Using offline semantic matching fallback.");
      const q = val.toLowerCase().trim();
      const matches = masterColleges.filter(col => 
        col.name.toLowerCase().includes(q) ||
        col.city.toLowerCase().includes(q) ||
        col.state.toLowerCase().includes(q) ||
        col.events.some(evt => evt.category.toLowerCase().includes(q) || evt.name.toLowerCase().includes(q))
      ).map(col => col.id);
      setAiMatches(matches);
    } finally {
      setAiLoading(false);
    }
  };

  // Selection states for comparison
  const [selectedCompareIds, setSelectedCompareIds] = useState<string[]>([]);
  const [compareOpen, setCompareOpen] = useState<boolean>(false);

  // College Details Drawer (More Details panel)
  const [currentCollege, setCurrentCollege] = useState<College | null>(null);
  const [drawerOpen, setDrawerOpen] = useState<boolean>(false);

  // State filtering logic
  const filteredColleges = useMemo(() => {
    let result = masterColleges;

    // Filter by State
    if (selectedState !== 'All') {
      result = result.filter(col => col.state === selectedState);
    }

    // Filter by Search Query
    if (searchQuery.trim() !== '') {
      if (isAiMode) {
        if (aiMatches !== null) {
          result = result.filter(col => aiMatches.includes(col.id));
        }
      } else {
        const q = searchQuery.toLowerCase().trim();
        result = result.filter(col => 
          col.name.toLowerCase().includes(q) || 
          col.city.toLowerCase().includes(q) || 
          col.state.toLowerCase().includes(q) ||
          col.examAccepted.some(ex => ex.toLowerCase().includes(q)) ||
          col.famousFest.toLowerCase().includes(q) ||
          (col.events && col.events.some(evt => 
            evt.category.toLowerCase().includes(q) ||
            evt.name.toLowerCase().includes(q)
          ))
        );
      }
    }

    // Filter by Event Category
    if (activeEventFilter !== 'All') {
      result = result.filter(col => 
        col.events && col.events.some(evt => evt.category === activeEventFilter)
      );
    }

    // Sorting Logic
    return [...result].sort((a, b) => {
      if (sortBy === 'name') {
        return a.name.localeCompare(b.name);
      } else if (sortBy === 'established') {
        return a.established - b.established;
      }
      return 0;
    });
  }, [masterColleges, selectedState, activeEventFilter, searchQuery, sortBy]);

  // Comparison helpers
  const selectedCompareColleges = useMemo(() => {
    return masterColleges.filter(col => selectedCompareIds.includes(col.id));
  }, [masterColleges, selectedCompareIds]);

  const handleToggleCompare = (id: string) => {
    setSelectedCompareIds(prev => {
      if (prev.includes(id)) {
        return prev.filter(item => item !== id);
      }
      // Upper clamp of 3 colleges
      if (prev.length >= 3) {
        alert("Bhai, compare tool mein up to 3 colleges hi add kiye jaa sakte hain.");
        return prev;
      }
      return [...prev, id];
    });
  };

  const handleRemoveCompare = (id: string) => {
    setSelectedCompareIds(prev => prev.filter(item => item !== id));
  };

  const handleClearCompare = () => {
    setSelectedCompareIds([]);
  };

  const handleViewDetails = (college: College) => {
    setCurrentCollege(college);
    setDrawerOpen(true);
  };

  const handleResetFilters = () => {
    setSelectedState('All');
    setActiveEventFilter('All');
    setSearchQuery('');
    setSortBy('name');
    setIsAiMode(false);
    setAiMatches(null);
    setAiRationale(null);
  };

  return (
    <div className="font-sans antialiased text-zinc-100 bg-black min-h-screen">
      <AnimatePresence mode="wait">
        {screen === 'welcome' ? (
          <motion.div key="welcome" className="w-full">
            <WelcomeScreen 
              onEnter={() => setScreen('explorer')} 
              totalColleges={masterColleges.length}
              totalStates={ALL_STATES.length}
            />
          </motion.div>
        ) : (
          <motion.div
            key="explorer"
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -15 }}
            transition={{ duration: 0.5, ease: "easeOut" }}
            className="flex flex-col min-h-screen"
          >
            {/* National Header Dashboard */}
            <header className="sticky top-0 z-30 bg-black/85 backdrop-blur-md border-b border-zinc-900 px-6 py-4">
              <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
                <div className="flex items-center gap-3 cursor-pointer" onClick={() => setScreen('welcome')}>
                  <span className="p-2 bg-white text-black rounded-xl shadow-[0_0_20px_rgba(255,255,255,0.15)]">
                    <GraduationCap className="w-6 h-6 stroke-[2.5px]" />
                  </span>
                  <div className="text-left">
                    <h1 className="text-md md:text-lg font-display font-semibold tracking-tight text-white flex items-center gap-1.5">
                      <span>India Engineering Directory</span>
                      <Sparkles className="w-3.5 h-3.5 text-blue-400 animate-pulse" />
                    </h1>
                    <p className="text-[10px] font-mono tracking-wider text-zinc-500 uppercase">National Institutional Directory Mapped</p>
                  </div>
                </div>

                {/* Tab select between directory and exams roadmap */}
                <div className="flex items-center gap-2.5">
                  <div className="bg-zinc-900 p-1.5 rounded-xl border border-zinc-800 flex gap-1">
                    <button
                      onClick={() => setActiveTab('list')}
                      className={`px-4 py-2 text-xs font-mono uppercase font-semibold rounded-lg transition-all cursor-pointer ${activeTab === 'list' ? 'bg-zinc-800 text-white shadow-sm' : 'text-zinc-400 hover:text-zinc-200'}`}
                    >
                      Institutes Map
                    </button>
                    <button
                      onClick={() => setActiveTab('exams')}
                      className={`px-4 py-2 text-xs font-mono uppercase font-semibold rounded-lg transition-all cursor-pointer ${activeTab === 'exams' ? 'bg-zinc-800 text-white shadow-sm' : 'text-zinc-400 hover:text-zinc-200'}`}
                    >
                      Entrance Guides
                    </button>
                  </div>

                  <button
                    onClick={() => setScreen('welcome')}
                    className="p-2.5 rounded-xl bg-zinc-900 border border-zinc-800 text-zinc-400 hover:text-white transition-all cursor-pointer"
                    title="Return to Welcome Screen"
                  >
                    <span className="text-xs font-mono">BACK</span>
                  </button>
                </div>
              </div>
            </header>

            {/* Main Interactive Screen Dashboard */}
            <main className="flex-grow max-w-7xl mx-auto w-full p-4 md:p-6 space-y-6">
              
              {activeTab === 'exams' ? (
                /* Entrance guides tab screen transition */
                <motion.div
                  initial={{ opacity: 0, scale: 0.98 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ duration: 0.3 }}
                >
                  <ExamsCatalog />
                </motion.div>
              ) : (
                /* Main Directory List View tab */
                <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
                    
                    {/* Left State Filter Sidebar (Desktop-only flowing sidebar) */}
                    <div className="lg:col-span-1">
                      <div className="bg-zinc-900/60 border border-zinc-800 rounded-2xl p-4 hidden lg:block text-left space-y-4 shadow-lg">
                        <div className="flex items-center justify-between pb-2 border-b border-zinc-800/50">
                          <span className="text-xs font-mono uppercase text-zinc-500 tracking-wider">States & UTs</span>
                          <span className="text-[10px] font-mono text-blue-400 bg-blue-500/10 px-2 py-0.5 rounded border border-blue-500/20 font-bold">
                            {ALL_STATES.length} Mapped
                          </span>
                        </div>
                        
                        <div className="space-y-1 divide-y divide-zinc-800/20">
                          <button
                            onClick={() => setSelectedState('All')}
                            className={`w-full text-left px-3 py-2.5 rounded-lg text-xs transition-all cursor-pointer font-medium flex items-center border border-transparent hover:translate-x-0.5 duration-200 ${selectedState === 'All' ? 'bg-blue-500/10 border-l-[3px] border-blue-500 text-blue-400 font-semibold shadow-[0_2px_8px_rgba(59,130,246,0.06)]' : 'text-zinc-400 hover:bg-zinc-800/40 hover:text-zinc-200'}`}
                          >
                            <span>🌍 All India</span>
                          </button>
                          
                          {ALL_STATES.map(st => {
                            return (
                              <button
                                key={st}
                                onClick={() => setSelectedState(st)}
                                className={`w-full text-left px-3 py-2.5 rounded-lg text-xs transition-all cursor-pointer font-medium flex items-center border border-transparent hover:translate-x-0.5 duration-200 ${selectedState === st ? 'bg-blue-500/10 border-l-[3px] border-blue-500 text-blue-400 font-semibold shadow-[0_2px_8px_rgba(59,130,246,0.06)]' : 'text-zinc-400 hover:bg-zinc-800/40 hover:text-zinc-200'}`}
                              >
                                <span className="truncate">{st}</span>
                              </button>
                            );
                          })}
                        </div>
                      </div>
                    </div>

                  {/* Right main search, filter controls & list grid */}
                  <div className="lg:col-span-3 space-y-6">
                    
                    {/* Search and control filter widget */}
                    <div className="bg-zinc-900/60 border border-zinc-800/80 rounded-2xl p-4 md:p-5 space-y-4">
                      
                      <div className="grid grid-cols-1 md:grid-cols-12 gap-3">
                        {/* Interactive Search input */}
                        <form 
                          onSubmit={(e) => { 
                            e.preventDefault(); 
                            if (isAiMode) {
                              handleAiSearch(searchQuery); 
                            }
                          }} 
                          className="md:col-span-6 relative flex flex-col gap-2"
                        >
                          <div className="relative">
                            <Search className="w-4 h-4 text-zinc-500 absolute left-3.5 top-3.5" />
                            <input
                              type="text"
                              value={searchQuery}
                              onChange={(e) => {
                                const val = e.target.value;
                                setSearchQuery(val);
                                if (!isAiMode) {
                                  setAiMatches(null);
                                  setAiRationale(null);
                                }
                              }}
                              placeholder={isAiMode ? "Ask AI (e.g. Bihar govt college sports)..." : "Search by college name, city, fest, exam..."}
                              className={`w-full bg-black border text-zinc-200 text-xs rounded-xl pl-10 pr-[100px] py-3.5 focus:outline-none transition-all uppercase font-mono tracking-wide placeholder-zinc-600 ${isAiMode ? 'border-blue-500/50 focus:border-blue-400' : 'border-zinc-805 focus:border-zinc-700'}`}
                            />
                            
                            {/* Inner AI Mode Switch */}
                            <button
                              type="button"
                              onClick={() => {
                                const mode = !isAiMode;
                                setIsAiMode(mode);
                                if (!mode) {
                                  setAiMatches(null);
                                  setAiRationale(null);
                                } else if (searchQuery.trim()) {
                                  handleAiSearch(searchQuery);
                                }
                              }}
                              className={`absolute right-2.5 top-2.5 px-3 py-1.5 rounded-lg text-[10px] font-mono font-bold uppercase transition-all duration-300 flex items-center gap-1 cursor-pointer select-none ${
                                isAiMode 
                                  ? 'bg-white text-black font-black shadow-[0_0_12px_rgba(255,255,255,0.15)]' 
                                  : 'bg-zinc-900 border border-zinc-800 text-blue-405 hover:text-blue-305'
                              }`}
                              title={isAiMode ? "Disable Gemini AI Mode" : "Enable Gemini Semantic AI Search"}
                            >
                              <Sparkles className="w-3 h-3" />
                              <span>AI MODE</span>
                            </button>
                          </div>

                          {aiLoading && (
                            <div className="absolute right-3 top-[3.7rem] text-[10px] font-mono text-blue-400 flex items-center gap-1.5 bg-black border border-zinc-900 p-1.5 rounded-lg z-10">
                              <span className="w-2.5 h-2.5 rounded-full bg-blue-500 animate-ping" />
                              <span>Gemini Analyzing...</span>
                            </div>
                          )}
                        </form>

                        {/* Mobile select state layout option */}
                        <div className="md:col-span-3 lg:hidden relative">
                          <select
                            value={selectedState}
                            onChange={(e) => setSelectedState(e.target.value)}
                            className="w-full bg-black border border-zinc-800 text-zinc-300 rounded-xl px-4 py-3.5 text-xs focus:outline-none focus:border-zinc-700 appearance-none cursor-pointer"
                          >
                            <option value="All">🌍 All India</option>
                            {ALL_STATES.map(st => (
                              <option key={st} value={st}>{st}</option>
                            ))}
                          </select>
                        </div>

                        {/* Sort Dropdown */}
                        <div className="md:col-span-3 relative">
                          <select
                            value={sortBy}
                            onChange={(e) => setSortBy(e.target.value)}
                            className="w-full bg-black border border-zinc-800 text-zinc-300 rounded-xl px-4 py-3.5 text-xs focus:outline-none focus:border-zinc-700 appearance-none cursor-pointer font-mono"
                          >
                            <option value="name">🔤 Sort: ALPHABETICAL</option>
                            <option value="established">⚙️ Sort: ESTABLISHED</option>
                          </select>
                        </div>

                        {/* Reset Filters Option Button */}
                        <div className="md:col-span-3">
                          <button
                            onClick={handleResetFilters}
                            className="w-full bg-black hover:bg-zinc-900 border border-zinc-850 hover:border-zinc-750 text-zinc-400 hover:text-white transition-all rounded-xl py-3.5 text-xs font-mono uppercase font-bold flex items-center justify-center gap-1.5 cursor-pointer"
                          >
                            <RotateCcw className="w-3.5 h-3.5" />
                            <span>Reset Filters</span>
                          </button>
                        </div>
                      </div>

                      {aiRationale && (
                        <div className="p-3.5 bg-blue-500/5 text-blue-400 border border-blue-500/10 rounded-xl text-xs font-mono font-light text-left flex items-start gap-2.5">
                          <Sparkles className="w-4 h-4 text-blue-400 flex-shrink-0 mt-0.5 animate-pulse" />
                          <span><strong>AI Search Insight:</strong> {aiRationale}</span>
                        </div>
                      )}

                      {/* Horizontal chips selector for Event Focus Categories */}
                      <div className="flex flex-wrap items-center gap-1.5 pt-1 border-t border-zinc-900/60">
                        <span className="text-[10px] font-mono text-zinc-500 uppercase tracking-widest mr-2">📅 Focus Event Category:</span>
                        {["All", "Hackathon", "Techfest", "Culture", "Sports"].map(cat => (
                          <button
                            key={cat}
                            onClick={() => setActiveEventFilter(cat)}
                            className={`px-3 py-1.5 rounded-lg text-[10px] font-bold font-mono transition-all uppercase cursor-pointer ${activeEventFilter === cat ? 'bg-blue-500/10 border border-blue-500/50 text-blue-400' : 'bg-black border border-zinc-855 hover:border-zinc-700 text-zinc-400'}`}
                          >
                            {cat}
                          </button>
                        ))}
                      </div>

                    </div>

                    {/* Results Count Summary Banner */}
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 px-1">
                      <div className="text-left font-light text-zinc-400 text-xs flex items-center gap-2">
                        <Info className="w-4 h-4 text-blue-405 flex-shrink-0" />
                        <span>
                          Filtered matches representing top engineering colleges 
                          {selectedState !== 'All' ? ` in ${selectedState}` : ' across India'}.
                        </span>
                      </div>
                      
                      {selectedCompareIds.length > 0 && (
                        <button
                          onClick={() => setCompareOpen(true)}
                          className="inline-flex items-center gap-1 px-3 py-1 bg-blue-500/10 border border-blue-500/30 text-blue-400 rounded-lg text-xs font-mono font-bold uppercase transition-all hover:bg-blue-500/20 cursor-pointer self-start"
                        >
                          <GitCompare className="w-3.5 h-3.5 stroke-[2.5px]" />
                          <span>Compare Selected ({selectedCompareIds.length})</span>
                        </button>
                      )}
                    </div>

                    {/* Colleges Grid staggered render with limit-tokens awareness */}
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-5">
                      <AnimatePresence mode="popLayout">
                        {filteredColleges.length > 0 ? (
                          filteredColleges.map((col, idx) => (
                            <motion.div
                              key={col.id}
                              layout
                              initial={{ opacity: 0, y: 15, scale: 0.98 }}
                              animate={{ opacity: 1, y: 0, scale: 1 }}
                              exit={{ opacity: 0, scale: 0.96, y: -10 }}
                              transition={{ 
                                duration: 0.35, 
                                delay: Math.min(idx * 0.025, 0.25), 
                                type: "spring", 
                                stiffness: 220, 
                                damping: 20 
                              }}
                            >
                              <CollegeCard
                                college={col}
                                isComparing={selectedCompareIds.includes(col.id)}
                                onToggleCompare={() => handleToggleCompare(col.id)}
                                onViewDetails={() => handleViewDetails(col)}
                                activeEventFilter={activeEventFilter}
                              />
                            </motion.div>
                          ))
                        ) : (
                          <motion.div 
                            initial={{ opacity: 0, y: 10 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0 }}
                            className="col-span-full py-16 text-center space-y-4 border border-dashed border-zinc-800 rounded-2xl bg-black"
                          >
                            <span className="p-4 rounded-full bg-zinc-900 border border-zinc-800 inline-block text-zinc-500">
                              <Filter className="w-8 h-8 mx-auto" />
                            </span>
                            <div className="space-y-1">
                              <p className="text-zinc-300 font-display font-medium text-sm">No Colleges Meet Matches Criteria</p>
                              <p className="text-zinc-500 text-xs font-light">Consider clearing filters or reset parameters search above.</p>
                            </div>
                            
                            <button
                              onClick={handleResetFilters}
                              className="px-4 py-2 bg-zinc-900 hover:bg-zinc-800 hover:text-white border border-zinc-800 text-xs rounded-lg text-blue-400 font-mono tracking-wider cursor-pointer"
                            >
                              Reset System Filters
                            </button>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>

                  </div>
                </div>
              )}

            </main>

                 {/* Persistent floating compare bar */}
            <AnimatePresence>
              {selectedCompareIds.length > 0 && (
                <motion.div
                  initial={{ y: "100%", opacity: 0 }}
                  animate={{ y: 0, opacity: 1 }}
                  exit={{ y: "100%", opacity: 0 }}
                  transition={{ type: "spring", stiffness: 260, damping: 25 }}
                  className="fixed bottom-0 inset-x-0 z-40 bg-zinc-950 border-t border-zinc-900 p-4 shadow-2xl flex flex-col sm:flex-row items-center justify-between gap-4 max-w-5xl mx-auto rounded-t-2xl"
                >
                  <div className="flex flex-col sm:flex-row items-center gap-3 text-center sm:text-left">
                    <span className="p-2 rounded-lg bg-blue-500/10 text-blue-400">
                      <GitCompare className="w-5 h-5 stroke-[2.5px]" />
                    </span>
                    <div>
                      <h4 className="text-xs font-mono font-bold text-zinc-200">College Comparison ({selectedCompareIds.length}/3)</h4>
                      <p className="text-[10px] text-zinc-500 hidden sm:block">Analyze characteristics and fests side-by-side</p>
                    </div>

                    {/* Chips array of active compare items */}
                    <div className="flex flex-wrap gap-1.5 max-w-md">
                      {selectedCompareColleges.map(col => (
                        <div key={col.id} className="inline-flex items-center gap-1.5 bg-black px-2 py-0.5 rounded-lg border border-zinc-900 text-[10px] text-zinc-300">
                          <span className="truncate max-w-[100px]">{col.name}</span>
                          <button 
                            onClick={() => handleRemoveCompare(col.id)}
                            className="text-zinc-500 hover:text-red-400 cursor-pointer"
                          >
                            <X className="w-3 h-3" />
                          </button>
                        </div>
                      ))}
                    </div>
                  </div>

                  <div className="flex items-center gap-2.5 w-full sm:w-auto">
                    <button
                      onClick={handleClearCompare}
                      className="w-1/2 sm:w-auto px-4 py-2 border border-zinc-800 hover:border-zinc-700 text-zinc-400 hover:text-red-400 font-mono text-xs rounded-xl cursor-pointer"
                    >
                      Clear All
                    </button>
                    <button
                      onClick={() => setCompareOpen(true)}
                      className="w-1/2 sm:w-auto px-6 py-2 bg-white hover:bg-zinc-100 text-black font-sans font-bold text-xs tracking-wider uppercase rounded-xl transition-all cursor-pointer shadow-md inline-flex items-center justify-center gap-1.5"
                    >
                      <span>Compare Now</span>
                      <ChevronRight className="w-3.5 h-3.5 stroke-[2.5px]" />
                    </button>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>

            {/* Compare dashboard matrix overlay modal */}
            <CompareModal
              selectedColleges={selectedCompareColleges}
              isOpen={compareOpen}
              onClose={() => setCompareOpen(false)}
              onRemove={handleRemoveCompare}
            />

            {/* More Details Side Panel Drawer Overlay */}
            <CollegeDetailsDrawer
              college={currentCollege}
              isOpen={drawerOpen}
              onClose={() => setDrawerOpen(false)}
              onToggleCompare={() => handleToggleCompare(currentCollege!.id)}
              isComparing={currentCollege ? selectedCompareIds.includes(currentCollege.id) : false}
              activeEventFilter={activeEventFilter}
            />

          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
